version: '3.8'

services:
  backend:
    build: .
    container_name: poker_backend
    restart: unless-stopped
    ports:
      - "80:3000"
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./game-be-env

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mongodb_data: